---
services:
  app:
    image: madeofpendletonwool/pinepods:latest
    ports:
      - 8040:8040
    labels:
      traefik.enable: true
      traefik.http.routers.pinepods.rule: Host(`pinepods.simn.io`)
      traefik.http.services.pinepods.loadbalancer.server.port: "8040"
    networks:
      - default
      - traefik
    environment:
      HOSTNAME: https://pinepods.simn.io
      DB_TYPE: postgresql
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: myS3curepass
      DB_NAME: pinepods_database
      VALKEY_HOST: valkey
      VALKEY_PORT: 6379
      DEBUG_MODE: false
      PUID: 3000
      PGID: 3000
      TZ: "{{ default_timezone }}"
    volumes:
      - /opt/pinepods/downloads:/opt/pinepods/downloads
      - /opt/pinepods/backups:/opt/pinepods/backups
    restart: unless-stopped
    depends_on:
      - db
      - valkey

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: pinepods_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myS3curepass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /opt/postgresql/pinepods:/var/lib/postgresql/data
    restart: unless-stopped

  valkey:
    image: valkey/valkey:8-alpine
    restart: unless-stopped

networks:
  traefik:
    name: internal
    external: true
