---
services:
  runner:
    image: code.forgejo.org/forgejo/runner:12.4.0
    user: "{{ docker_compose_user_id }}:994"
    volumes:
      - /opt/forgejo/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: forgejo-runner daemon -c config.yml
    environment:
      TZ: "{{ default_timezone }}"
      DOCKER_HOST: tcp://docker_proxy:2375
    restart: unless-stopped
    logging:
      driver: none

  docker_proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:v0.4.2
    restart: unless-stopped
    environment:
      BUILD: 1
      POST: 1
      CONTAINERS: 1
      INFO: 1
      IMAGES: 1
      VOLUMES: 1
      NETWORKS: 1
      ALLOW_START: 1
      ALLOW_STOP: 1
      ALLOW_RESTARTS: 1
      EXEC: 1
    tmpfs:
      - /run
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: none
