---
services:
  runner:
    image: code.forgejo.org/forgejo/runner:11.3.1@sha256:287433414b987b89896399683034818db198079053d84ca473aadb06ebad8b9f
    user: "{{ docker_compose_user_id }}:994"
    volumes:
      - /opt/forgejo/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: forgejo-runner daemon -c config.yml
    environment:
      TZ: "{{ default_timezone }}"
    restart: unless-stopped
    logging:
      driver: none
