---
services:
  runner:
    image: code.forgejo.org/forgejo/runner:12.1.2
    user: "{{ docker_compose_user_id }}:994"
    volumes:
      - /opt/forgejo/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: forgejo-runner daemon -c config.yml
    environment:
      TZ: "{{ default_timezone }}"
    restart: unless-stopped
    logging:
      driver: none
