---
# PowerDNS.pdns
pdns_config_specific:
  primary: true
  allow-axfr-ips: 192.168.1.114/32
  only-notify: ""
  also-notify: 192.168.1.114:5353

# caddy_ansible.caddy_ansible
caddy_adguard_host: dns01.simn.io
caddy_pdns_host: ns1.simn.io
