$ANSIBLE_VAULT;1.1;AES256
66626265633437306239316631363439323536393038633439383336373235626536666332636533
3330393134393031646635643231376632636364346338610a646361353639633533363962656333
62613562333437656339653437653530343235303539313965313535653962303165663334613161
3663306239306536660a356164383366373561626563613764366634323265346532313730303732
62376433363933346637646463316237316261303465353935386430663530333263316233646364
34666661616264363733353461363835326431636263306166366236336639613331333536626137
64316639663733653061623234323232306638323862373538333538306337313961373030363165
36336438653632626335373437613436613233343032656539663331333836663830333465306333
64363564373237306533626338366466616537313832333562653362363239636661643961316666
33313661386633366230663463393333653062323336373030363037343631386636306466313766
366338333236393061643135346530666337
