services:
  app:
    image: louislam/uptime-kuma:2.1.0
    volumes:
      - /opt/uptime-kuma/data:/app/data
    ports:
      - 3001:3001
    labels:
      traefik.enable: true
      traefik.http.routers.uptime.rule: Host(`uptime.simn.io`)
      traefik.http.services.uptime.loadbalancer.server.port: "3001"
    restart: unless-stopped
