---
services:
  app:
    image: ghcr.io/authelia/authelia:4.39.14@sha256:88f1494b6ac1174641770f106335ab67752d66e5822b4059badca220b5d6153b
    user: "{{ docker_compose_user_id }}:{{ docker_compose_group_id }}"
    restart: unless-stopped
    environment:
      TZ: "{{ default_timezone }}"
    volumes:
      - /opt/authelia/config:/config
    ports:
      - 9091:9091
    env_file: .env
    labels:
      traefik.enable: true
      traefik.http.routers.authelia.rule: Host(`auth.simn.io`)
      traefik.http.services.authelia.loadbalancer.server.port: "9091"

networks:
  default:
    name: internal
    external: true
