---
services:
  app:
    image: ghcr.io/authelia/authelia:4.39.15
    user: "{{ docker_compose_user_id }}:{{ docker_compose_group_id }}"
    restart: unless-stopped
    environment:
      TZ: "{{ default_timezone }}"
    volumes:
      - /opt/authelia/config:/config
    env_file: .env
    labels:
      traefik.enable: true
      traefik.http.routers.authelia.rule: Host(`auth.simn.io`)
      traefik.http.services.authelia.loadbalancer.server.port: "9091"

networks:
  default:
    name: internal
    external: true
