---
services:
  app:
    image: cyfershepard/jellystat:1.1.7
    environment:
      POSTGRES_IP: db
      POSTGRES_PORT: 5432
    env_file: .env
    labels:
      traefik.enable: true
      traefik.http.routers.jellystat.rule: Host(`jellystat.simn.io`)
      traefik.http.services.jellystat.loadbalancer.server.port: "3000"
    networks:
      - default
      - traefik
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:17.7
    environment:
      POSTGRES_DB: jfstat
    env_file: .env
    volumes:
      - /opt/postgresql/jellystat:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  traefik:
    name: internal
    external: true
