$ANSIBLE_VAULT;1.1;AES256
65653265303031393062323961626266376630636564313835666530316238336534376431646532
3730396562313032316331336430623163613137343231300a363863353132346662636334303239
31343330643532613931643834656231613133313964653035373439303938373865343563336333
3033393933663836320a623039313765666133663939373362366662396162366539303237616139
62646463346561643065333263386130666163616166313339313830653139353631303563363065
36363231366138653064353636306338396532653461613039316336303533616436366265356631
35326630336239663965643739623937356161626437626666396137306430623362656337656234
62383733663363663364636665643461633533383830353539393430363735663937366566313330
63613164396464366131386332333666623236386565356530636638666337343431663564313566
37306532643138386164326263323936303930653439353865366531313966336465323461343138
366562333363663163313063383561323830
