---

services:
  app:
    image: ghcr.io/jittering/traefik-kop:0.19.2@sha256:d3cac649ced91dd2d808a0e16147fa32cfa9c7db8249ccba5a70ef6f61682011
    env_file: .env
    environment:
      REDIS_ADDR: proxy01.simn.io:6379
      DOCKER_HOST: tcp://docker-socket-proxy:2375
      BIND_IP: "{{ ansible_hostname }}.simn.io"
    restart: unless-stopped

networks:
  default:
    name: internal
    external: true
