---

services:
  app:
    image: ghcr.io/jittering/traefik-kop:0.19.1@sha256:f591da1bdc8e57f88a2f2c90c5d1619dc056e9106f3ea8d5aca92ba04ab441a6
    env_file: .env
    environment:
      REDIS_ADDR: proxy01.simn.io:6379
      DOCKER_HOST: tcp://docker-socket-proxy:2375
      BIND_IP: "{{ ansible_hostname }}.simn.io"
    restart: unless-stopped

networks:
  default:
    name: internal
    external: true
