---

services:
  app:
    image: ghcr.io/jittering/traefik-kop:0.19.4
    environment:
      REDIS_ADDR: docker01.priv.simn.io:6379
      DOCKER_HOST: tcp://docker-socket-proxy:2375
      BIND_IP: monitoring01.priv.simn.io
    restart: unless-stopped

networks:
  default:
    name: internal
    external: true
