collections:
  - name: community.general
    version: 12.2.0
  - name: community.docker
    version: 5.0.4
  - name: community.proxmox
    version: 1.5.0
  - name: ansible.posix
    version: 2.1.0
  - name: wzzrd.gitea
    version: 1.0.6
  - name: artis3n.tailscale
    version: 1.1.0

roles:
  - name: oefenweb.postfix
    version: v3.8.1
  - name: geerlingguy.docker
    version: 7.9.0
  - name: geerlingguy.mysql
    version: 6.0.0
  - name: geerlingguy.security
    version: 3.0.0
  - name: geerlingguy.nut_client
    version: 2.0.0
  - name: geerlingguy.redis
    version: 1.9.1
  - name: simoncaron.pve_nvidia_passthrough
    version: 3.0.0
  - name: simoncaron.pve_acme
    version: 1.5.0
  - name: nickjj.acme_sh
    version: v1.1.0
  - name: bcook254.adguardhome
    version: 107.71.0
  - name: simoncaron.traefik
    version: 1.0.2
  - name: lae.proxmox
    src: https://github.com/lae/ansible-role-proxmox
    version: v1.10.0
