---
services:
  app:
    image: ghcr.io/fallenbagel/jellyseerr:2.7.3
    environment:
      TZ: "{{ default_timezone }}"
      LOG_LEVEL: info
    labels:
      traefik.enable: true
      traefik.http.routers.jellyseerr.rule: Host(`jellyseerr.simn.io`)
      traefik.http.services.jellyseerr.loadbalancer.server.port: "5055"
    volumes:
      - /opt/jellyseerr/config:/app/config
    restart: unless-stopped

networks:
  default:
    name: internal
    external: true
