$ANSIBLE_VAULT;1.1;AES256
66383663393365393536623963386162323161336633633166373066303762643837623235303863
6631373437633765666134383434366565306461363562300a313732316631323639343162626236
61363237373331616464383831396464343531333761653238333463306462316262393364396631
6236383564353234340a323162633638313063633532653933316362386565373030373566383234
33653139333531636238303732376265396536323236373230653461613161636437663464376362
39303332343434636265613038663234636539613363313036636566656439656365646230656362
39313461663831616330643634383534633837356330613364353836633632666364316439626133
39376362323435626637376161333530313064303435653134323364333636383134303438386565
62643732623437373833303239346330363166373132383032616162613364376234303632343433
3761306634326531623662633365323465643363663435663935
