---
services:
  app:
    image: brandawg93/peanut:5.17.0@sha256:723f51f562cc44a340c38d1db98809d3b07474a44616943c741884feeceb8c99
    env_file: .env
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.peanut.rule: Host(`peanut.simn.io`)
      traefik.http.services.peanut.loadbalancer.server.port: "8085"
    ports:
      - 8085:8080
    environment:
      NUT_HOST: truenas01.simn.io
      NUT_PORT: 3493
      WEB_PORT: 8080
      INFLUX_HOST: https://influxdb.simn.io:8086
      INFLUX_ORG: homelab
      INFLUX_BUCKET: nut
